### ISSUE TITLE
Add ability to set Lore to item

### ISSUE THREAD

**Issue by cupang-afk** [alexcrea/CustomAnvil#53]
**Describe the solution you'd like**
    -

**Idea how to integrate it**
to add
- using book and quil and put in anvil just like you enchant an item to set lore (Item + Book and Quil = Item with lore)
- or using paper and put in anvil and use anvil naming to set lore (Item + Paper = Item with lore)

to remove
- using empty book and quil
- or using paper but switched place

**Additional context**
if book and quil is used, the lore text is obtain from the book and quil content

**Comment by alexcrea** [comment]
Looks like a good Idea. 
Would you think maybe add the paper name and use empty paper to remove lore (or a line of lore ?) maybe bé better ?

**Comment by cupang-afk** [comment]
> Looks like a good Idea. Would you think maybe add the paper name and use empty paper to remove lore (or a line of lore ?) maybe bé better ?

that would be great addition to flexibility to obtain lore in vanilla way

but to pick one, i prefer the book and quil method, since it need and extra step to get making it feel a bit more precious, and also support multi line by default
and to remove the lore from item, instead of removing the lore entirely from the item, why don't transfer it to the book and quil as its content

for the papers name idea, i don't think it's gonna be good with multi line support unless one understand about line break `\n` escape
or maybe using some placeholder like <newline> for minimessage

but im open with the idea though

sorry for late reply

**Comment by alexcrea** [comment]
Don't worry about late reply. I myself don't really have time to work on it rn

Note: I want default config of the plugin to act as much as vanilla as possible (with 1 exception). So I was more thinking of paper & book & quil to be toggled individually and at admin choice
Also: I was more thinking of paper to extract/add only 1 lore line. The last of first (maybe this toggled too)

Also, will probably add a permission for use like color as some plugin may have the bad* idea to store data on lore
(*personal opinion)

**Comment by alexcrea** [comment]
Beta release on https://github.com/alexcrea/CustomAnvil/releases/tag/v1.10.0-beta.1

**Comment by cupang-afk** [comment]
> Beta release on https://github.com/alexcrea/CustomAnvil/releases/tag/v1.10.0-beta.1

did some quick test

- `do_consume` didn't do anything if set true or false, it just consume the book of quill or paper whatever the settings is (but im not sure since i reload the config using anvilconfigreload and didn't proper restart the server)
- enchant squared item have some of the enchanting name lost ( i didn't test all the enchantment so there is a probability ;) )

here is the item
![Image](https://github.com/user-attachments/assets/73f09522-5e2b-4818-97d0-7944692f66d0)

here is when i "remove" the lore using paper
![Image](https://github.com/user-attachments/assets/ee19785a-f9a6-4c9f-9732-7babb6472207)

here is when i do with book and quill
![Image](https://github.com/user-attachments/assets/40013b33-3908-4f1c-bda2-84c395ae8224)

maybe it because enchant squared use lore to add their enchant name

adding lore is okay though, it work 👍 



and 
question

will this support minimessage ?, i dont mind legacy color code though, it just minimessage can do hex support out of the box too, but well i see the plugin itself didn't offer minimessage

**Comment by alexcrea** [comment]
Hum, for do_consume it is weird. Could you give me a configuration that seems to not works so I can test locally ?

I guess I can try to make it only try to remove non ench² lore entry

I think I looked into minimessage in the past but decided it was more verbose and not good for the anvil rename field do not have a lot of place to display things
but with book & quill there a lot more space
also if you enable hex yo ucan just #123456 for example in custom anvil

**Comment by alexcrea** [comment]
> my small braincell suggest me to save the custom anvil lore into nbt data entry so whenever the plugin add or remove the lore it search/regex search the role, delete it, and re-apply the added/edited role so it can preserve even after other plugin edit the role directly

what ? I'm not sure what you're talking about

**Comment by cupang-afk** [comment]
> > my small braincell suggest me to save the custom anvil lore into nbt data entry so whenever the plugin add or remove the lore it search/regex search the role, delete it, and re-apply the added/edited role so it can preserve even after other plugin edit the role directly
> 
> what ? I'm not sure what you're talking about

im not sure either so nevermind!!

**Comment by cupang-afk** [comment]
> Hum, for do_consume it is weird. Could you give me a configuration that seems to not works so I can test locally ?

i set do_consume to true this time (when it false, it still consume the item so i change it to true to see the changes)

```yaml
#
# It is recommended that you use /configanvil to edit theses config.
# You can still manually edit here if you like to. but if you do, don't forget to /anvilconfigreload after you changes !
#

# All anvil cost will be capped to limit_repair_value if enabled.
#
# In other words:
# For any anvil cost greater than limit_repair_value, Cost will be set to limit_repair_value.
limit_repair_cost: true

# Max cost value the Anvil can get to.
#
# Valid values include 0 to 1000.
# Cost will be displayed as "Too Expensive":
# - If Cost is above 39
# - And replace_too_expensive is disabled (false)
limit_repair_value: 100

# Whether the anvil's cost limit should be removed entirely.
#
# The anvil will still visually display "Too Expensive" if "replace_too_expensive" is disabled
# However, the action will be completable if xp requirement is meet.
remove_repair_limit: true

# Whenever anvil cost is above 39 should display the true price and not "Too Expensive".
#
# However, when bypassing "Too Expensive", anvil price will be displayed as Green.
# If the action is not completable, the cost will still be displayed as "Too expensive".
# That mean you also need to change other settings like remove_repair_limit or limit_repair_cost.
#
# Require ProtocoLib.
replace_too_expensive: true

# XP Level amount added to the anvil when the item is repaired by another item of the same type
#
# Valid values include 0 to 1000
item_repair_cost: 2

# XP Level amount added to the anvil when the item is renamed
#
# Valid values include 0 to 1000
item_rename_cost: 1

# XP Level amount added to the anvil when the item is repaired by an "unit"
# For example: a Diamond on a Diamond Sword
# What's considered unit for what can be edited on the unit repair configuration.
#
# Valid values include 0 to 1000
unit_repair_cost: 1

# XP Level amount added to the anvil when a sacrifice enchantment
# conflict with one of the left item enchantment
#
# Valid values include 0 to 1000
sacrifice_illegal_enchant_cost: 1

# Allow using color code and hexadecimal color.
#
# Color code are prefixed by "&" and hexadecimal color by "#".
# Color code will not be applied if it colors nothing. "&&" can be used to write "&".
allow_color_code: true
allow_hexadecimal_color: false

# Toggle if color should only be applicable if the player a certain permission.
#
# permission are "ca.color.code" for use of color code and "ca.color.hex" for use of hexadecimal color.
permission_needed_for_color: true

# Xp cost if the player use color in the items name on rename.
#
# Valid values include 0 to 1000.
use_of_color_cost: 0

# Default limit to apply to any enchants missing from enchant_limits
#
# Valid values include 1 to 1000
default_limit: 5

# Override limits for specific enchants
#
# Enchantments not listed here will use the value of default_limit
#
# Overrides provided default from aqua_affinity to depth_strider won't change effect with extra levels
#
# Valid range of 1 - 255 for each enchantment
enchant_limits:
  minecraft:aqua_affinity: 1
  minecraft:binding_curse: 1
  minecraft:channeling: 1
  minecraft:flame: 1
  minecraft:infinity: 1
  minecraft:mending: 1
  minecraft:multishot: 1
  minecraft:silk_touch: 1
  minecraft:vanishing_curse: 1
  minecraft:depth_strider: 5 # anything more than 3 is treated as 3 by the game
  minecraft:protection: 6
  minecraft:fire_protection: 6
  minecraft:blast_protection: 6
  minecraft:projectile_protection: 6
  minecraft:feather_falling: 6
  minecraft:thorns: 5
  minecraft:respiration: 5
  minecraft:sharpness: 7
  minecraft:smite: 7
  minecraft:bane_of_arthropods: 7
  minecraft:knockback: 4
  minecraft:fire_aspect: 4
  minecraft:looting: 5
  minecraft:sweeping: 5
  minecraft:sweeping_edge: 5
  minecraft:efficiency: 7
  minecraft:unbreaking: 5
  minecraft:fortune: 5
  minecraft:power: 7
  minecraft:punch: 4
  minecraft:luck_of_the_sea: 5
  minecraft:lure: 5
  minecraft:frost_walker: 4
  minecraft:impaling: 7
  minecraft:riptide: 5
  minecraft:loyalty: 5
  minecraft:piercing: 6
  minecraft:quick_charge: 5
  minecraft:soul_speed: 5
  minecraft:swift_sneak: 5
  minecraft:density: 7
  minecraft:breach: 6
  minecraft:wind_burst: 5
  enchantssquared:sunforged: 1
  enchantssquared:kinship: 3
  enchantssquared:rejuvenation: 3
  enchantssquared:lava_walker: 2
  enchantssquared:speed_boost: 2
  enchantssquared:jump_boost: 2
  enchantssquared:night_vision: 1
  enchantssquared:water_breathing: 1
  enchantssquared:haste: 2
  enchantssquared:metabolism: 2
  enchantssquared:strength: 2
  enchantssquared:vigorous: 5
  enchantssquared:lucky: 3
  enchantssquared:curse_durability: 3
  enchantssquared:curse_heavy: 2
  enchantssquared:curse_hunger: 2
  enchantssquared:withering: 3
  enchantssquared:stunning: 2
  enchantssquared:slowing: 2
  enchantssquared:nausea: 2
  enchantssquared:weakening: 2
  enchantssquared:poisoning: 3
  enchantssquared:blinding: 3
  enchantssquared:crushing: 3
  enchantssquared:arrow_aoe: 3
  enchantssquared:toxic: 3
  enchantssquared:shielding: 3
  enchantssquared:knockback_protection: 2
  enchantssquared:vitality: 5
  enchantssquared:illuminated: 1
  enchantssquared:auto_replant: 1
  enchantssquared:bonus_exp: 3
  enchantssquared:vampiric: 2
  enchantssquared:beheading: 2
  enchantssquared:soulbound: 1
  enchantssquared:chemical_shield: 0
  enchantssquared:potion_potency_buff: 2
  enchantssquared:tradeoff_berserk: 3
  enchantssquared:plating: 3
  enchantssquared:trident_sharpness: 5
  enchantssquared:grappling: 2
  enchantssquared:lava_resistance: 1
  enchantssquared:perforating: 3
  enchantssquared:shield_downer: 3
  enchantssquared:telekinesis: 1
  enchantssquared:lightning: 3
  enchantssquared:tree_feller: 1
  enchantssquared:pulling: 3
  enchantssquared:rapid_shot: 3
  enchantssquared:streak_damage: 2
  enchantssquared:ground_stomping: 2
  enchantssquared:exploding: 3
  enchantssquared:damage_reduction: 3

# Multipliers used to calculate the enchantment's value in repair/combining
#
# Values here are pulled from the fandom wiki:
# https://minecraft.fandom.com/wiki/Anvil_mechanics#Costs_for_combining_enchantments
#
# If an enchantment is missing values here, or is less than 0, it will default to 0
#
# Calculated as: [Enchantment lvl] * [multiplier]
#
# With default values protection 4 would have a value of 4 when
# coming from either a book (4 * 1) or an item (4 * 1)
enchant_values:
  minecraft:aqua_affinity:
    item: 4
    book: 2
  minecraft:bane_of_arthropods:
    item: 2
    book: 1
  minecraft:binding_curse:
    item: 8
    book: 4
  minecraft:blast_protection:
    item: 4
    book: 2
  minecraft:channeling:
    item: 8
    book: 4
  minecraft:depth_strider:
    item: 4
    book: 2
  minecraft:efficiency:
    item: 1
    book: 1
  minecraft:flame:
    item: 4
    book: 2
  minecraft:feather_falling:
    item: 2
    book: 1
  minecraft:fire_aspect:
    item: 4
    book: 2
  minecraft:fire_protection:
    item: 2
    book: 1
  minecraft:fortune:
    item: 4
    book: 2
  minecraft:frost_walker:
    item: 4
    book: 2
  minecraft:impaling:
    item: 4
    book: 2
  minecraft:infinity:
    item: 8
    book: 4
  minecraft:knockback:
    item: 2
    book: 1
  minecraft:looting:
    item: 4
    book: 2
  minecraft:loyalty:
    item: 1
    book: 1
  minecraft:luck_of_the_sea:
    item: 4
    book: 2
  minecraft:lure:
    item: 4
    book: 2
  minecraft:mending:
    item: 4
    book: 2
  minecraft:multishot:
    item: 4
    book: 2
  minecraft:piercing:
    item: 1
    book: 1
  minecraft:power:
    item: 1
    book: 1
  minecraft:projectile_protection:
    item: 2
    book: 1
  minecraft:protection:
    item: 1
    book: 1
  minecraft:punch:
    item: 4
    book: 2
  minecraft:quick_charge:
    item: 2
    book: 1
  minecraft:respiration:
    item: 4
    book: 2
  minecraft:riptide:
    item: 4
    book: 2
  minecraft:silk_touch:
    item: 8
    book: 4
  minecraft:sharpness:
    item: 1
    book: 1
  minecraft:smite:
    item: 2
    book: 1
  minecraft:soul_speed:
    item: 8
    book: 4
  minecraft:swift_sneak:
    item: 8
    book: 4
  minecraft:sweeping:
    item: 4
    book: 2
  minecraft:sweeping_edge:
    item: 4
    book: 2
  minecraft:thorns:
    item: 8
    book: 4
  minecraft:unbreaking:
    item: 2
    book: 1
  minecraft:vanishing_curse:
    item: 8
    book: 4
  minecraft:density:
    item: 2
    book: 1
  minecraft:breach:
    item: 4
    book: 2
  minecraft:wind_burst:
    item: 4
    book: 2
  enchantssquared:sunforged:
    item: 1
    book: 1
  enchantssquared:kinship:
    item: 1
    book: 1
  enchantssquared:rejuvenation:
    item: 1
    book: 1
  enchantssquared:lava_walker:
    item: 1
    book: 1
  enchantssquared:speed_boost:
    item: 1
    book: 1
  enchantssquared:jump_boost:
    item: 1
    book: 1
  enchantssquared:night_vision:
    item: 1
    book: 1
  enchantssquared:water_breathing:
    item: 1
    book: 1
  enchantssquared:haste:
    item: 1
    book: 1
  enchantssquared:metabolism:
    item: 1
    book: 1
  enchantssquared:strength:
    item: 1
    book: 1
  enchantssquared:vigorous:
    item: 1
    book: 1
  enchantssquared:lucky:
    item: 1
    book: 1
  enchantssquared:curse_durability:
    item: 1
    book: 1
  enchantssquared:curse_heavy:
    item: 1
    book: 1
  enchantssquared:curse_hunger:
    item: 1
    book: 1
  enchantssquared:withering:
    item: 1
    book: 1
  enchantssquared:stunning:
    item: 1
    book: 1
  enchantssquared:slowing:
    item: 1
    book: 1
  enchantssquared:nausea:
    item: 1
    book: 1
  enchantssquared:weakening:
    item: 1
    book: 1
  enchantssquared:poisoning:
    item: 1
    book: 1
  enchantssquared:blinding:
    item: 1
    book: 1
  enchantssquared:crushing:
    item: 1
    book: 1
  enchantssquared:arrow_aoe:
    item: 1
    book: 1
  enchantssquared:toxic:
    item: 1
    book: 1
  enchantssquared:shielding:
    item: 1
    book: 1
  enchantssquared:knockback_protection:
    item: 1
    book: 1
  enchantssquared:vitality:
    item: 1
    book: 1
  enchantssquared:illuminated:
    item: 1
    book: 1
  enchantssquared:auto_replant:
    item: 1
    book: 1
  enchantssquared:bonus_exp:
    item: 1
    book: 1
  enchantssquared:vampiric:
    item: 1
    book: 1
  enchantssquared:beheading:
    item: 1
    book: 1
  enchantssquared:soulbound:
    item: 1
    book: 1
  enchantssquared:chemical_shield:
    item: 1
    book: 1
  enchantssquared:potion_potency_buff:
    item: 1
    book: 1
  enchantssquared:tradeoff_berserk:
    item: 1
    book: 1
  enchantssquared:plating:
    item: 1
    book: 1
  enchantssquared:trident_sharpness:
    item: 1
    book: 1
  enchantssquared:grappling:
    item: 1
    book: 1
  enchantssquared:lava_resistance:
    item: 1
    book: 1
  enchantssquared:perforating:
    item: 1
    book: 1
  enchantssquared:shield_downer:
    item: 1
    book: 1
  enchantssquared:telekinesis:
    item: 1
    book: 1
  enchantssquared:lightning:
    item: 1
    book: 1
  enchantssquared:tree_feller:
    item: 1
    book: 1
  enchantssquared:pulling:
    item: 1
    book: 1
  enchantssquared:rapid_shot:
    item: 1
    book: 1
  enchantssquared:streak_damage:
    item: 1
    book: 1
  enchantssquared:ground_stomping:
    item: 1
    book: 1
  enchantssquared:exploding:
    item: 1
    book: 1
  enchantssquared:damage_reduction:
    item: 1
    book: 1

# Disable enchantment merging for level above the set value
# Enchantment merging is when, for example, 2 unbreaking II book combine to give sharpness III
# But Enchantment above this value can still be applied. following the previous example, we could still apply a unbreaking III book to a sword
# Even if disable-merge-over of unbreaking is set to 2
# -1 mean enchantment merge for this enchantment is not disabled. default to -1 if absent.
disable-merge-over:
  # Sharpness is set to -1. it equivalent to it not being set to anything (and work as vanilla)
  minecraft:sharpness: -1
# If uncommented. 2 unbreaking II book would not give an unbreaking III book. but unbreaking III book can still be applied
# minecraft:unbreaking: 2

# Whether to show debug logging
debug_log: false

# Whether to show verbose debug logging
debug_log_verbose: false

# In case something when wrong with CustomAnvil packet manager.
# If you see "missing class exception" or similar you may test this.
# If enabled and Protocolib absent or disabled "Replace to expensive" will not work.
# ProtocoLib may also be used if the server is in an "unsupported" version even if this option is disabled.
force_protocolib: false

configVersion: 1.8.0
lowMinecraftVersion: '1.21'
lore_edit:
  book_and_quil:
    append:
      enabled: true
      fixed_cost: 1
      do_consume: true
      per_line_cost: 0
      allow_color_code: true
      allow_hexadecimal_color: true
      use_cost: 0
    remove:
      enabled: true
      fixed_cost: 1
      do_consume: false
      per_line_cost: 0
      remove_color_on_remove: false
      remove_color_cost: 0
    use_permission: true
  paper:
    append_line:
      enabled: true
      fixed_cost: 1
      do_consume: true
      allow_color_code: true
      allow_hexadecimal_color: true
      use_cost: 0
    remove_line:
      enabled: true
      fixed_cost: 1
      do_consume: true
      remove_color_on_remove: false
      remove_color_cost: 0
    use_permission: true
    order: end

```

**Comment by cupang-afk** [comment]
> also if you enable hex yo ucan just #123456 for example in custom anvil

i didn't see it, thanks for letting me know

**Comment by alexcrea** [comment]
tested on my server and do consume seems to work as expected ? (inverted every true to false & false to true. then re using default)
are you sure you did not changed do_consume for, for example, book remove instead of book append ?

**Comment by alexcrea** [comment]
tested WITH enchantment squared can confirm

**Comment by cupang-afk** [comment]
> tested on my server and do consume seems to work as expected ? (inverted every true to false & false to true. then re using default) are you sure you did not changed do_consume for, for example, book remove instead of book append ?

https://github.com/user-attachments/assets/2504a32a-88d9-401f-91ac-e0f7c1343d25


i properly update the server and reset the config now

still issue


server
```
> version
[00:21:36 INFO]: Checking version, please wait...
[00:21:37 INFO]: This server is running Leaf version 1.21.4-264-ver/1.21.4@f7db1ed (2025-03-21T13:00:25Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
* You are running the latest version
Previous: 1.21.4-DEV-0275694 (MC: 1.21.4)
```

```yaml
# Settings for lore modification
lore_edit:
  book_and_quil:
    # Permission is ca.lore_edit.book
    use_permission: true
    append:
      # If adding lore using book & quil is enabled
      enabled: true
      # Cost used every time
      fixed_cost: 1
      # Cost used for every lore line added
      per_line_cost: 0
      # Use left item vanilla cost penalty if any
      shared_increase: false
      # Increase shared left item cost penalty
      shared_additive: false
      # If adding the lore consume the book & quil
      do_consume: false
      # Allow using color code and hexadecimal color when editing lore via book & quil
      #
      # Color code are prefixed by "&" and hexadecimal color by "#"
      # Color code will not be applied if it colors nothing. "&&" can be used to write "&"
      allow_color_code: true
      allow_hexadecimal_color: true
      use_cost: 0
    
    remove:
      # If removing lore using book & quil is enabled
      enabled: true
      # Cost used every time
      fixed_cost: 1
      # Cost used for every lore line removed
      per_line_cost: 0
      # Use left item vanilla cost penalty if any
      shared_increase: false
      # Increase shared left item cost penalty
      shared_additive: false
      # If removing the lore consume the book & quil
      do_consume: false
      # If the color should get back to color code or hex format
      remove_color_on_remove: true
      # Cost of replacing colors
      remove_color_cost: 0
  
  paper:
    # Permission is ca.lore_edit.paper
    use_permission: true
    # what order should the lines should get added/removed (start/end, if invalid or not present will be end)
    order: end
    
    append_line:
      # If adding lore line using paper is enabled
      enabled: true
      # Cost used every time
      fixed_cost: 1
      # Use left item vanilla cost penalty if any
      shared_increase: false
      # Increase shared left item cost penalty
      shared_additive: false
      # If adding the lore line consume the paper
      do_consume: false
      # Allow using color code and hexadecimal color when editing lore via book & quil
      #
      # Color code are prefixed by "&" and hexadecimal color by "#"
      # Color code will not be applied if it colors nothing. "&&" can be used to write "&"
      allow_color_code: true
      allow_hexadecimal_color: true
      color_use_cost: 0
      use_cost: 0
    
    remove_line:
      # If removing lore line using paper is enabled
      enabled: true
      # Cost used every time
      fixed_cost: 1
      # Use left item vanilla cost penalty if any
      shared_increase: false
      # Increase shared left item cost penalty
      shared_additive: false
      # If removing the lore line consume the paper
      do_consume: false
      # If the color should get back to color code or hex format
      remove_color_on_remove: true
      # Cost of replacing colors
      remove_color_cost: 0
```
